# Site configuration
title: "Sean Jain Ellis"
subtitle: "Software Development and Life Adventures"
description: "Personal website and blog covering computing, travel and other life adventures."
github: "https://github.com/bandarji"

# Theme configuration (using custom theme)
plugins:
- jekyll-remote-theme
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections for separate blogs
collections:
  coding:
    output: true
    permalink: /coding/:title/
  hiatus:
    output: true
    permalink: /hiatus/:title/

# Defaults for blog posts
defaults:
  - scope:
      path: "_coding"
      type: "coding"
    values:
      layout: "post"
      author: "Sean Jain Ellis"
  - scope:
      path: "_hiatus"
      type: "hiatus"
    values:
      layout: "post"
      author: "Sean Jain Ellis"
